import Breadcrumbs from "../components/Breadcrumbs";
import { pageMetadata } from "../lib/seo";
import Link from "next/link";import SiteShell from "../components/SiteShell";
const resources = [
  { title: "Drug information A to Z", text: "Browse prescription and over-the-counter medicine information from the National Library of Medicine.", href: "https://medlineplus.gov/druginformation.html", action: "Browse MedlinePlus medicines" },
  { title: "Medicine labels", text: "Find labeling supplied to the FDA, including prescribing information and patient instructions, on DailyMed.", href: "https://dailymed.nlm.nih.gov/dailymed/", action: "Find labels on DailyMed" },
  { title: "Understanding interactions", text: "Read FDA information about medicine, food, and supplement interactions to discuss with your pharmacist.", href: "https://www.fda.gov/drugs/resources-drugs/drug-interactions-what-you-should-know", action: "Read the FDA interaction guide" },
  { title: "Vitamins and supplements", text: "Explore MedlinePlus links to NIH information about herbs and dietary supplements.", href: "https://medlineplus.gov/druginfo/herb_All.html", action: "Browse herbs and supplements" },
  { title: "Medication safety after 50", text: "Prepare a complete medicine list and practical questions for a review with your care team.", href: "/health-news/prepare-for-a-medication-review", action: "Read the MyVeta medication review guide" },
  { title: "Questions about your medicines", text: "Review FDA guidance for older adults on medicine use and conversations with healthcare professionals.", href: "https://www.fda.gov/drugs/information-consumers-and-patients-drugs/you-age-you-and-your-medicines", action: "Read the FDA older adult medicine guide" },
];
export const metadata = pageMetadata({
  "title": "Medication Safety and Review Preparation",
  "description": "Prepare for a medication review with questions for your pharmacist and guidance on organizing prescriptions, supplements, and safety concerns.",
  "path": "/drugs"
});

export default function Drugs(){return <SiteShell><section className="page-hero"><div className="container"><Breadcrumbs items={[{ name: "Home", path: "/" }, { name: "Medication safety", path: "/drugs" }]} /><p className="eyebrow">MEDICATION GUIDE</p><h1>Drugs and supplements</h1><p>Look up common uses, side effects, safety warnings, interactions, and practical questions. Always follow the instructions from your prescriber or pharmacist.</p></div></section><section className="container page-content"><div className="drug-search"><h2>Find information about a medicine</h2><p>Use the medicine library on MedlinePlus, from the National Library of Medicine.</p><a className="primary" href="https://medlineplus.gov/druginformation.html">Open the MedlinePlus medicine library</a></div><div className="tool-grid">{resources.map(x=><article key={x.title}><h2>{x.title}</h2><p>{x.text}</p><Link href={x.href}>{x.action}</Link></article>)}</div><section className="medication-guide"><h2>Prepare for a medication review</h2><div className="info-grid"><div><h3>Bring a complete list</h3><p>Include prescriptions, over-the-counter products, vitamins, herbal products, allergies, doses, and the time each item is taken.</p></div><div><h3>Ask about each medicine</h3><p>Understand why you take it, how long you may need it, what happens if you miss a dose, and which side effects require a call.</p></div><div><h3>Use one pharmacy when possible</h3><p>A consistent pharmacy can make it easier to review the complete medication list for interactions and duplication.</p></div><div><h3>Do not make changes alone</h3><p>Stopping some medicines suddenly can be harmful. Discuss any concern, cost issue, or side effect before changing treatment.</p></div></div></section><div className="medical-alert"><b>Medication safety notice</b><p>Never start, stop, split, or change the dose of a medicine based only on website information. Contact a pharmacist or qualified healthcare professional.</p></div></section></SiteShell>}
